### ISSUE TITLE
reproducing /example fails with regards to KakaoSDK

### ISSUE THREAD

**Issue by gewure** [fysoul17/firebase_auth_simplify#4]
**Describe the bug**
when trying to run the app in /example i get the following stack:

**To Reproduce**
1. new flutter project from sources in /example
2. build it

**Expected behavior**
i guess it should work

**Stacktrace**
Running "flutter pub get" in heysilly...
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(18327): FATAL EXCEPTION: main
E/AndroidRuntime(18327): Process: heysilly.heysilly, PID: 18327
E/AndroidRuntime(18327): java.lang.RuntimeException: Unable to resume activity {heysilly.heysilly/heysilly.heysilly.MainActivity}: java.lang.IllegalStateException: Session is not initialized. Call KakaoSDK#init first.
E/AndroidRuntime(18327): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
E/AndroidRuntime(18327): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
E/AndroidRuntime(18327): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
E/AndroidRuntime(18327): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(18327): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(18327): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(18327): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(18327): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(18327): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(18327): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18327): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(18327): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(18327): Caused by: java.lang.IllegalStateException: Session is not initialized. Call KakaoSDK#init first.
E/AndroidRuntime(18327): 	at com.kakao.auth.Session.getCurrentSession(Session.java:109)
E/AndroidRuntime(18327): 	at com.kakao.auth.KakaoSDK$1.onActivityResumed(KakaoSDK.java:70)
E/AndroidRuntime(18327): 	at android.app.Application.dispatchActivityResumed(Application.java:436)
E/AndroidRuntime(18327): 	at android.app.Activity.dispatchActivityResumed(Activity.java:1265)
E/AndroidRuntime(18327): 	at android.app.Activity.onResume(Activity.java:1789)
E/AndroidRuntime(18327): 	at io.flutter.embedding.android.FlutterActivity.onResume(FlutterActivity.java:543)
E/AndroidRuntime(18327): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
E/AndroidRuntime(18327): 	at android.app.Activity.performResume(Activity.java:7939)
E/AndroidRuntime(18327): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
E/AndroidRuntime(18327): 	... 11 more

**Flutter Doctor -v**
no problems

**Comment by fysoul17** [comment]
I also found that there is an issue with the old Kakao package.

Since there are many changes for the old Kakao package which leads to a certain crash, I switched to a new Kakao package which is now supported by the Kakao community officially.

Please update to the latest version of the package.  v1.x.x

**Comment by fysoul17** [comment]
Closing as there are no updates anymore.
